FROM node:20-alpine AS build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
RUN apk add --no-cache jq openssl \
    && wget -qO- https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-alpine-linux-amd64-v0.6.1.tar.gz \
       | tar -xz -C /usr/local/bin

ENV PUBLIC_HTML=/var/www/public/
COPY .docker/nginx /etc/nginx/
COPY .docker/add-env-vars.sh /docker-entrypoint.d/01-add-env-vars.sh
COPY --from=build /usr/src/app/build /var/www/public/
RUN cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.aicorte \
    && cp -a /etc/nginx/sites.d /etc/nginx/sites.d.aicorte \
    && printf '%s\n' \
       '#!/bin/sh' \
       'set -eu' \
       'cp /etc/nginx/conf.d/default.conf.aicorte /etc/nginx/conf.d/default.conf' \
       'rm -rf /etc/nginx/sites.d' \
       'cp -a /etc/nginx/sites.d.aicorte /etc/nginx/sites.d' \
       > /docker-entrypoint.d/00-reset-nginx.sh \
    && chmod +x /docker-entrypoint.d/00-reset-nginx.sh \
                /docker-entrypoint.d/01-add-env-vars.sh

EXPOSE 80
